version: 2
updates:
  - package-ecosystem: "npm" # Replace "npm" with your package manager
    directory: "/" # Location of package manifests (e.g., package.json for npm)
    schedule:
      interval: "weekly"
