anthropic_pricing:
  claude_3_5_sonnet:
    context_window: 200000
    input_cost_per_mtok: 3.0
    output_cost_per_mtok: 15.0
    prompt_caching_write: 3.75
    prompt_caching_read: 0.30
    notes: "Most intelligent model, 50% discount with Batches API"
  claude_3_5_haiku:
    context_window: 200000
    input_cost_per_mtok: 0.8
    output_cost_per_mtok: 4.0
    prompt_caching_write: 1.0
    prompt_caching_read: 0.08
    notes: "Fastest and most cost-effective model, 50% discount with Batches API"
  claude_3_opus:
    context_window: 200000
    input_cost_per_mtok: 15.0
    output_cost_per_mtok: 75.0
    prompt_caching_write: 18.75
    prompt_caching_read: 1.50
    notes: "Powerful model for complex tasks, 50% discount with Batches API"
