openai_pricing:
  gpt_3_5_turbo:
    input: 0.0005
    output: 0.0015
  gpt_3_5_turbo_16k:
    input: 0.003
    output: 0.006
  gpt_4:
    input: 0.01
    output: 0.03
  gpt_4_32k:
    input: 0.03
    output: 0.06
  gpt_4o:
    input: 0.0025
    output: 0.01
  gpt_4o_mini:
    input: 0.00015
    output: 0.0006
  gpt_4_turbo:
    input: 0.01
    output: 0.03
  o1:
    input: 0.015
    output: 0.06
  o1_mini:
    input: 0.003
    output: 0.012
  gpt_4o_realtime_preview:
    input: 0.005
    output: 0.02
  gpt_4o_mini_realtime_preview:
    input: 0.0006
    output: 0.0024
